# Generated by Django 4.2.7 on 2024-01-14 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter_price',
            name='price',
            field=models.CharField(choices=[('1000 To 3000', '1000 To 3000'), ('3000 To 6000', '3000 To 6000'), ('6000 To 9000', '6000 To 9000'), ('9000 To 11000', '9000 To 11000'), ('11000 To 20000', '11000 To 20000'), ('20000 To 40000', '20000 To 40000')], max_length=60),
        ),
    ]
