# Generated by Django 4.2.7 on 2024-01-15 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_order_additional_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='contry',
            new_name='country',
        ),
    ]
