# Generated by Django 4.2.7 on 2024-01-30 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_wishlistitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WishlistItem',
        ),
    ]
