# Generated by Django 4.2.7 on 2024-01-30 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_delete_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Ordered', 'Ordered'), ('Shipping', 'Order Shipping'), ('Pending', 'Order Pending'), ('Completed', 'Order Completed')], default='Ordered', max_length=20, null=True),
        ),
    ]
