# Generated by Django 4.2.7 on 2024-01-30 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
