# Generated by Django 4.2.7 on 2024-01-30 11:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_orderitems_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='date',
        ),
        migrations.AddField(
            model_name='orderitems',
            name='phone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitems',
            name='status',
            field=models.CharField(choices=[('Ordered', 'Ordered'), ('Shipping', 'Order Shipping'), ('Pending', 'Order Pending'), ('Completed', 'Order Completed')], default='Ordered', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='tracking_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=10, unique=True),
        ),
    ]
