# Generated by Django 4.2.7 on 2024-01-30 11:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_order_status_remove_orderitems_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='status',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='tracking_id',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Ordered', 'Ordered'), ('Shipping', 'Order Shipping'), ('Pending', 'Order Pending'), ('Completed', 'Order Completed')], default='Ordered', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=10, unique=True),
        ),
    ]
