# Generated by Django 4.2.7 on 2024-01-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_orderitems_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_id',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
