# Generated by Django 4.2.7 on 2024-01-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_order_tracking_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tracking_id',
        ),
        migrations.AddField(
            model_name='order',
            name='track',
            field=models.CharField(default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
