# Generated by Django 4.2.7 on 2024-01-30 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_order_tracking_id_order_track'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='phone',
        ),
    ]
