# Generated by Django 4.2.7 on 2024-01-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_remove_orderitems_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='track',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
