# Generated by Django 4.2.7 on 2024-01-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_order_track'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='track',
        ),
        migrations.AddField(
            model_name='orderitems',
            name='status',
            field=models.CharField(choices=[('Ordered', 'Ordered'), ('Shipping', 'Order Shipping'), ('Pending', 'Order Pending'), ('Completed', 'Order Completed')], default='Ordered', max_length=20, null=True),
        ),
    ]
