# Generated by Django 4.2.7 on 2024-01-30 12:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_orderitems_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=10, unique=True),
        ),
    ]
