# Generated by Django 4.2.7 on 2024-01-30 14:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_order_tracking_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Ordered', 'Ordered'), ('Shipping', 'Order Shipping'), ('Way', 'On the Way'), ('Completed', 'Order Completed')], default='Ordered', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
